services:
  - type: web
    name: wordsnap-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTESSERACT_PATH
        value: /usr/bin/tesseract 